macro_path: "/tmp/macros"
local_fs_path: "/tmp/localfs"
log_level: 2
log_file: "/tmp/fluidnc.log"

fluidnc:
  api_url: "http://fluidnc.local"
  websocket:
    url: "ws://fluidnc.local:81"
  stream:
    simple: true
    rx_buffer_size: 128
    line_buffer_size: 16
