// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {state} from '../models';
import {fileman} from '../models';

export function ClearProbeHistory():Promise<void>;

export function Config():Promise<config.Config>;

export function DelFile(arg1:string,arg2:string):Promise<void>;

export function ExportProbeHistory():Promise<void>;

export function GetFile(arg1:string,arg2:string):Promise<string>;

export function GetLastProbe():Promise<state.ProbeResult>;

export function GetProbeHistory():Promise<Array<state.ProbeResult>>;

export function ImportProbeHistory():Promise<void>;

export function IsLocalFS():Promise<boolean>;

export function IsMacroFS():Promise<boolean>;

export function IsRemoteFS():Promise<boolean>;

export function IsUsbFS():Promise<boolean>;

export function ListDrives():Promise<Array<string>>;

export function ListFiles(arg1:string,arg2:string):Promise<fileman.FileList>;

export function PutFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunFile(arg1:string,arg2:string):Promise<void>;

export function SendAsync(arg1:string):Promise<void>;

export function SendAsyncRaw(arg1:any):Promise<void>;

export function SendWait(arg1:string):Promise<Array<string>>;

export function TestIngest():Promise<void>;

export function TestSender():Promise<void>;
