// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearProbeHistory() {
  return window['go']['app']['App']['ClearProbeHistory']();
}

export function GetProbeHistory() {
  return window['go']['app']['App']['GetProbeHistory']();
}

export function SendAsync(arg1) {
  return window['go']['app']['App']['SendAsync'](arg1);
}

export function SendAsyncRaw(arg1) {
  return window['go']['app']['App']['SendAsyncRaw'](arg1);
}

export function SendWait(arg1) {
  return window['go']['app']['App']['SendWait'](arg1);
}

export function TestFunc() {
  return window['go']['app']['App']['TestFunc']();
}
