// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {state} from '../models';

export function ClearProbeHistory():Promise<void>;

export function GetLastProbe():Promise<state.ProbeResult>;

export function GetProbeHistory():Promise<Array<state.ProbeResult>>;

export function SendAsync(arg1:string):Promise<void>;

export function SendAsyncRaw(arg1:any):Promise<void>;

export function SendWait(arg1:string):Promise<Array<string>>;

export function TestIngest():Promise<void>;

export function TestSender():Promise<void>;
