// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearProbeHistory() {
  return window['go']['app']['App']['ClearProbeHistory']();
}

export function Emitter(arg1, arg2) {
  return window['go']['app']['App']['Emitter'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['app']['App']['Send'](arg1);
}

export function SendRaw(arg1) {
  return window['go']['app']['App']['SendRaw'](arg1);
}

export function Test() {
  return window['go']['app']['App']['Test']();
}
