// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearProbeHistory() {
  return window['go']['app']['App']['ClearProbeHistory']();
}

export function Config() {
  return window['go']['app']['App']['Config']();
}

export function GetFile(arg1, arg2) {
  return window['go']['app']['App']['GetFile'](arg1, arg2);
}

export function GetLastProbe() {
  return window['go']['app']['App']['GetLastProbe']();
}

export function GetProbeHistory() {
  return window['go']['app']['App']['GetProbeHistory']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['app']['App']['ListFiles'](arg1, arg2);
}

export function RunFile(arg1) {
  return window['go']['app']['App']['RunFile'](arg1);
}

export function SaveMacro(arg1, arg2) {
  return window['go']['app']['App']['SaveMacro'](arg1, arg2);
}

export function SendAsync(arg1) {
  return window['go']['app']['App']['SendAsync'](arg1);
}

export function SendAsyncRaw(arg1) {
  return window['go']['app']['App']['SendAsyncRaw'](arg1);
}

export function SendWait(arg1) {
  return window['go']['app']['App']['SendWait'](arg1);
}

export function TestIngest() {
  return window['go']['app']['App']['TestIngest']();
}

export function TestSender() {
  return window['go']['app']['App']['TestSender']();
}

export function UploadFile(arg1, arg2) {
  return window['go']['app']['App']['UploadFile'](arg1, arg2);
}
