// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emitter(arg1:string,arg2:Array<any>):Promise<void>;

export function Send(arg1:string):Promise<void>;

export function SendRaw(arg1:any):Promise<void>;
